name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

    # Start node
    - name: Era Test Node Action
      uses: dutterbutter/era-test-node-action@36ffd2eefd46dc16e7e2a8e1715124400ec0a3ba # v1

    # Setup pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.11.0

    - name: Use Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        node-version: lts/Iron
        cache: 'pnpm'

    # Install dependencies for contracts/gateway/sdk
    - name: Install dependencies
      run: pnpm install -r --frozen-lockfile

    # Build SDK
    - name: Build SDK
      run: pnpm nx build sdk

    # Build contracts and generate types
    - name: Build contracts
      run: pnpm nx build contracts

    # Run contract tests
    - name: Run contract test
      run: pnpm nx test contracts

    # Run E2E tests
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
      working-directory: packages/demo-app
    - name: Run e2e tests
      run: pnpm nx e2e demo-app
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: packages/demo-app/playwright-report/
        retention-days: 3
