name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    # Start node
    - name: Era Test Node Action
      uses: dutterbutter/era-test-node-action@v1

    # NPM install for contracts/gateway/sdk
    - name: Use latest Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/Iron
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install contracts dependencies
      working-directory: ./packages/contracts
      run: npm ci
    - name: Install gateway dependencies
      working-directory: ./packages/gateway
      run: npm ci
    - name: Install sdk dependencies
      working-directory: ./packages/sdk
      run: npm ci

    # Build SDK
    - name: Build SDK
      working-directory: ./packages/sdk
      run: npm run build:cjs

    # Link SDK to other packages
    - name: Link SDK to contracts
      run: |
        cd packages/sdk
        npm link
        cd ../contracts
        npm link zksync-account
    - name: Link SDK to gateway
      run: |
        cd packages/sdk
        npm link
        cd ../gateway
        npm link zksync-account

    # Start the Gateway
    - name: Run Gateway in the background
      working-directory: ./packages/gateway
      run: |
        npm run dev -- --port 3002 &
        for attempt in {1..20}; do sleep 1; if (curl localhost:3002| head -n1 | grep -Ev 'Nuxt Dev server is starting...|Starting Nuxt...'); then echo ready; break; fi; echo waiting...; done

    # Run e2e tests
    - name: Run e2e test
      working-directory: ./packages/contracts
      run: npm run test -- --typecheck

