name: "Preview Auth Server"
on:
  pull_request:
  workflow_dispatch:

env:
  HUSKY: 0
  CI: true

jobs:
  build_and_preview:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    outputs:
      output_urls: "${{ steps.preview_deploy.outputs.urls }}"
    steps:
      - uses: actions/checkout@v4 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -r --frozen-lockfile

      - name: "Build gateway"
        run: pnpm nx build sdk

      - name: "Build gateway"
        run: pnpm nx build-static gateway

      - name: Deploy preview
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_AUTH_SERVER_STAGING }}"
          projectId: zksync-auth-server-staging
          target: zksync-auth-server-staging
